# Generated by Django 4.2.11 on 2026-02-14 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0003_prescription_appointment_reminder_1h_sent_and_more'),
        ('transcription_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('is_edited', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='consultation_app.appointment')),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='transcription_app.transcription')),
            ],
        ),
    ]
